### PR TITLE
Bug fix/memory leak

### LINKED ISSUE #91: Navbar sign out potential memory leak
When signing out from the profile page, the browser has the potential to lock up.

### PR DESCRIPTION
**Pull request by davidjes97**
Currently does not fix memoryLeak just updates profile pic for now and disables photo upload button

### CODE REVIEW

File: src/pages/profilePage.jsx [hunk 1]
```diff
@@ -1,145 +1,180 @@
...
-        imgUrl: ''
-    };
-    const [imageAsFile, setImageAsFile] = useState('');
-    const [tempName, setTempName] = useState(props.displayName);
-    const [imageAsURL, setImageAsUrl] = useState(allInputs);
-    const [profileImageURL, setProfileImageURL] = useState('');
-
-
-    /*Code adapted from Tallan Groberg
+  const allInputs = {
```
Comment (BrotherB1) [inline src/pages/profilePage.jsx]: Is there a reason we have this as a dict instead of just a single value? I don't really see what the use of this variable is.

File: src/pages/profilePage.jsx [hunk 2]
```diff
@@ -1,145 +1,180 @@
...
-            storage.ref('images').child(mySubString).getDownloadURL().then(fireBaseUrl => {
-                setImageAsUrl(prevObject => ({
-                    ...prevObject,
-                    imgUrl: fireBaseUrl
-                }))
-            })});
-        })
+  const handleImageAsFile = e => {
+    const image = e.target.files[0];
+    setImageAsFile(imageFile => image);
```
Comment (BrotherB1) [inline src/pages/profilePage.jsx]: Also, if you are going for a dict, wouldn't you want this to be "imgUrl => image" to associate the key it was instantiated with?

File: src/pages/profilePage.jsx (hunk 1 above)
Comment (davidjes97) [reply src/pages/profilePage.jsx]: Made these changes

File: src/pages/profilePage.jsx (hunk 2 above)
Comment (davidjes97) [reply src/pages/profilePage.jsx]: Made these changes

**Comment by davidjes97** [comment]
Just fixed my memory leak error

**Review by KellyHancox — DISMISSED** [review]

**Review by BrotherB1 — APPROVED** [review]
